FIXUP: BACKPORT: FROMLIST: mm: multigenerational lru: Kconfig
0-day reports: include/linux/page-flags-layout.h:104:2:
	error: #error "Not enough bits in page flags"

This is because some config options consume many bits in page flags
and leave not enough spare bits for the multigenerational lru. Making
those options and the multigenerational lru mutually exclusive fixes
the build error.

BUG=b:123039911
TEST=Built

Disallow-Recycled-Builds: test-failures
Reported-by: kernel test robot <lkp@intel.com>
Signed-off-by: Yu Zhao <yuzhao@google.com>
Change-Id: I891aae56d491a207201fe80eebae185ada1ebc56
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3018899
Tested-by: Yu Zhao <yuzhao@chromium.org>
Reviewed-by: Guenter Roeck <groeck@chromium.org>
Commit-Queue: Yu Zhao <yuzhao@chromium.org>