CHROMIUM: evdi: Makefile: Fix build with C=1
The original Makefile is mangling the LINUXINCLUDE var and causing
sparse to fail.

Fixes:

command-line: note: in included file (through builtin):
./include/linux/kconfig.h:7:11:
	error: unable to open 'generated/autoconf.h'
make[4]: *** [scripts/Makefile.build:279:
	drivers/gpu/drm/evdi/evdi_platform_drv.o] Error 1

We also take this chance to clean-up the Makefile

BUG=b:185885455
TEST=CROSS_COMPILE=aarch64-linux-gnu- ARCH=arm64 make W=1 C=1

Signed-off-by: Ricardo Ribalda <ribalda@chromium.org>
Change-Id: Ia4851d843c2cd247922b3c5e6b90d361eb953c6c
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3010098
Reviewed-by: Guenter Roeck <groeck@chromium.org>